config/routes.rb
H5::Application.routes.draw do
  resources :page_templates

  resources :works

end

app/models/page_template.rb
class PageTemplate < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_templates_controller.rb
class PageTemplatesController < ApplicationController
  # GET /page_templates
  # GET /page_templates.json
  def index
    @page_templates = PageTemplate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page_templates }
    end
  end

  # GET /page_templates/1
  # GET /page_templates/1.json
  def show
    @page_template = PageTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page_template }
    end
  end

  # GET /page_templates/new
  # GET /page_templates/new.json
  def new
    @page_template = PageTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page_template }
    end
  end

  # GET /page_templates/1/edit
  def edit
    @page_template = PageTemplate.find(params[:id])
  end

  # POST /page_templates
  # POST /page_templates.json
  def create
    @page_template = PageTemplate.new(params[:page_template])

    respond_to do |format|
      if @page_template.save
        format.html { redirect_to @page_template, notice: 'Page template was successfully created.' }
        format.json { render json: @page_template, status: :created, location: @page_template }
      else
        format.html { render action: "new" }
        format.json { render json: @page_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /page_templates/1
  # PUT /page_templates/1.json
  def update
    @page_template = PageTemplate.find(params[:id])

    respond_to do |format|
      if @page_template.update_attributes(params[:page_template])
        format.html { redirect_to @page_template, notice: 'Page template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_templates/1
  # DELETE /page_templates/1.json
  def destroy
    @page_template = PageTemplate.find(params[:id])
    @page_template.destroy

    respond_to do |format|
      format.html { redirect_to page_templates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # GET /works
  # GET /works.json
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work = Work.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render json: @work, status: :created, location: @work }
      else
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.json
  def update
    @work = Work.find(params[:id])

    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work = Work.find(params[:id])
    @work.destroy

    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_templates_helper.rb
module PageTemplatesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "H5" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">H5</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<html class="dom-mode"><head>
    <meta charset="utf-8">
    <meta name="mobileoptimized" content="0">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <meta name="screen-orientation" content="portrait">
    <meta name="browsermode" content="application">
    <title>吴鹏的初页</title>
    <link href="//static01.cloud7.com.cn/assets/a48c584b/content/style/first-page-min.css" rel="stylesheet">
</head>
<body class="first">

<div class="body">
	<div class="loading-next-page-tips">
		<div class="circle">
			
		</div>
	</div>
	<div class="page animation-run">
		<div class="layout-component-from-data" style="overflow: hidden; -webkit-transform: translate3d(0px, 0px, 0px) scale(1) rotateZ(0rad); transform: translate3d(0px, 0px, 0px) scale(1) rotateZ(0rad); opacity: 1; z-index: 0; position: absolute; left: 0px; top: 0px; width: 100%; height: 100%;">
			<img src="http://img01.cloud7.com.cn/371a9a98071ed29cbd09f3f8d4102e38.jpg" style="width: 100%; margin-left: 0px; margin-top: 0px;">
		</div>
	</div>
	<div id="slide-tips" class="switch-tips"></div>
	</div>
	<div class="slide-arrow switch-tips">
	
	</div>
</body>
</html>

app/views/page_templates/_form.html.erb
<%= form_for(@page_template) do |f| %>
  <% if @page_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page_template.errors.count, "error") %> prohibited this page_template from being saved:</h2>

      <ul>
      <% @page_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/page_templates/edit.html.erb
<h1>Editing page_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @page_template %> |
<%= link_to 'Back', page_templates_path %>

app/views/page_templates/index.html.erb
<h1>Listing page_templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @page_templates.each do |page_template| %>
  <tr>
    <td><%= page_template.name %></td>
    <td><%= page_template.content %></td>
    <td><%= link_to 'Show', page_template %></td>
    <td><%= link_to 'Edit', edit_page_template_path(page_template) %></td>
    <td><%= link_to 'Destroy', page_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page template', new_page_template_path %>

app/views/page_templates/new.html.erb
<h1>New page_template</h1>

<%= render 'form' %>

<%= link_to 'Back', page_templates_path %>

app/views/page_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @page_template.name %>
</p>

<p>
  <b>Content:</b>
  <%= @page_template.content %>
</p>


<%= link_to 'Edit', edit_page_template_path(@page_template) %> |
<%= link_to 'Back', page_templates_path %>

app/views/works/_form.html.erb
<%= form_for @work, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                works_path, :class => 'btn' %>
  </div>
<% end %>

app/views/works/edit.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/works/index.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= link_to work.id, work_path(work) %></td>
        <td><%= work.name %></td>
        <td><%=l work.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_work_path(work), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      work_path(work),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_work_path,
            :class => 'btn btn-primary' %>

app/views/works/new.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/works/show.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @work.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              works_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_work_path(@work), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              work_path(@work),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>